#!/bin/bash

set -e 
# Check release version in Dockerfile and setup.py

source .venv/bin/activate
VERSION=`python -c "import tomlkit; print(tomlkit.load(open('pyproject.toml', 'rb'))['project']['version'])"`

echo ${VERSION}

twine upload dist/whyis_fediverse-${VERSION}-py3-none-any.whl

git tag -f v${VERSION}

git push
